version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${LOCAL_PGUSER:-myuser}
      POSTGRES_PASSWORD: ${LOCAL_PGPASSWORD:-mypassword}
      POSTGRES_DB: ${LOCAL_PGDB:-mydb}
    ports:
      - "${LOCAL_PGPORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
